kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    when:
      event:
        - tag
      branch:
        - master
      
    settings:
      repo: 
        from_secret: PLUGIN_REPO
      username:
        from_secret: PLUGIN_USERNAME
      auth:
        from_secret: PLUGIN_AUTH
      tags:
      - latest
      - ${DRONE_TAG}