kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    when:
      event:
        - tag
      branch:
        - master
      
    settings:
      tags:
      - latest
      - ${DRONE_TAG}